version: "3.1"
services:
   bag2pc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/opt/bag2pc
    networks:
      - bag2pc
      - nginx-load-balancer
    restart: always
networks:
  bag2pc:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
